### PR TITLE
fix: Fix invalid date parsing in org-social posts

### LINKED ISSUE #3: Bug: all posts have invalid date
All posts show "invalid date" instead of the real date. Same is true for "joined on".

# Expected

Date from the ID field is properly parsed as per the spec: https://github.com/tanrax/org-social/blob/main/README.md

# Actual

All dates say "invalid date"

### PR DESCRIPTION
**Pull request by simon-duchastel**
## Summary

Fixes #3, resolving the bug where all posts displayed "invalid date" instead of proper timestamps. The fix includes robust timestamp parsing, better error handling, and improved date formatting throughout the application.

## Key Changes Made

- **Added robust `parseOrgSocialTimestamp` utility** with validation for RFC 3339 format compliance
- **Filters out posts with invalid dates** to prevent UI corruption
- **Enhanced inline property parsing** for org-social format compatibility (the parsing library `uniorg` doesn't properly parse headlines without text)

## Testing
Added tests: run with: `npm run test`

### CODE REVIEW

File: web/components/Post.jsx [hunk 1]
```diff
@@ -6,17 +6,24 @@ import styles from './Post.module.css'
...
+          date = parsed
+        } else {
+          date = new Date(timestamp)
+        }
       }
       
-      // Check if date is valid
-      if (!date || isNaN(date.getTime())) {
+      // Ensure we have a valid Date object
+      if (!(date instanceof Date) || isNaN(date.getTime())) {
```
Comment (simon-duchastel) [inline web/components/Post.jsx:26]: Same comment - the business logic should guarantee the date is well-formed! Maybe make it a string or something and have it be opaque to the UI?

File: web/components/Profile.jsx [hunk 2]
```diff
@@ -17,25 +16,20 @@ function Profile({ user, posts, onProfileClick, allUsers }) {
...
+        const earliestPost = posts[posts.length - 1]
+        const date = earliestPost.parsedDate
+        
+        if (date instanceof Date && !isNaN(date.getTime())) {
+          return date.toLocaleDateString('en-US', {
+            year: 'numeric',
+            month: 'long'
+          })
+        }
+        return 'Recently'
```
Comment (simon-duchastel) [inline web/components/Profile.jsx:31]: Let's figure out why the dates aren't parsing? I like 'Recently' as a fallback, but it's an unexpected case (and it's always happening for join date! Why?)

File: web/utils/apiClient.js [hunk 3]
```diff
@@ -1,5 +1,40 @@
 const API_BASE_URL = typeof window !== 'undefined' ? '' : 'http://localhost:3001'
 
+/**
+ * Convert date strings back to Date objects after JSON deserialization
+ */
+function restoreDateObjects(data) {
```
Comment (simon-duchastel) [inline web/utils/apiClient.js:6]: Why do we need to restoreDateObjects? This smells of poor encapsulation between the UI and the business logic. This is inelegant and shouldn't be necessary - date guarantees should be enforced by the logic in the backend and then not worried about by the UI
